source 'https://rubygems.org'

# Specify your gem's dependencies in jekyll-markdown-block.gemspec
group :jekyll_plugins do
  gem "octopress-ink", path: "../../ink"
  gem "octopress-gist", path: "../"
end

gem "redcarpet"
gem "RedCloth"
