source 'https://rubygems.org'

# Specify your gem's dependencies in jekyll-markdown-block.gemspec
group :jekyll_plugins do
  gem "octopress-gist", path: "../../"
end

gem "colorator"
gem "redcarpet"
gem "RedCloth"
gem "jekyll", "~> 1.0.0"
